### ISSUE TITLE
Rebrand SubstratumNode

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#146]
Take a turn through the whole codebase, including documentation, using the new names instead of Substratum and SubstratumNode. Clarify and repeat in documentation that this repo was forked from SubstratumNode: we're not plagiarizing, just rebranding.

Rename the ClandestiNet/ClandestiNode repository, and get a Pipelines installation working for Continuous Integration.

Redirect: Don't rebrand NodeUI yet. Wait until we have a new logo and new colors.

**Comment by kauri-hero** [comment]
We will also need to add the contributing aspect to each of the HEAD sections of code, possibly mentioning the code is a fork of Substratum Node, copyright Substratum LLC

This link should help:
https://www.gnu.org/licenses/gpl-3.0.html#howto
