### ISSUE TITLE
Prepare Testing Demo

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#227]
Prepare a demo for testing one of the completed cards, perhaps GH-186.

The following steps should be shown:

1. Downloading TNT.
2. Setting up TNT.
3. Display and explanation of card wall from testing perspective.
4. Watching a build go through Pipelines.
5. Identifying the results in MASQ-results.
6. Downloading the results.
7. Installing the binaries in TNT.
8. Doing an orientation run-through with TNT.
9. Demonstrating and testing the functionality of GH-186 (or whatever) using TNT.
10. Discussion of improving the process via having testers in grooming meetings.

Wow. That might be a long meeting.

**Comment by kauri-hero** [comment]
Reviewing the full video once more after preliminary watch - awesome job @dnwiebe 

Will be time stamping the sections and providing this on the YouTube description, and also trimming each major section into 'Chapters' to create smaller videos for public consumption.

**Comment by kauri-hero** [comment]
Posted onto YouTube and will trim into smaller segments.

Video is excellent and very well detailed.
