### ISSUE TITLE
CLI - New Execution Mode

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#242]
Invent yet another execution mode, along with --generate-wallet and 
	--dump-config and the rest, where the Node comes up, opens a small
	UIGateway, and listens for connections on a well-defined port (probably 
	5333). (This will eventually be the only way to start the Node, but to 
	keep it in service as these changes are made, this should start out as an 
	additional mode of operation.) When the connection is made:
	
	if a daemon has already been forked, with a secondary UI port, and is 
			still running:
		Respond to any traffic across the connection with an instruction to 
				redirect to the secondary UI port
	else
		if a 'start' command arrives:
			Fork the Node as a daemon in standard mode, passing on all the 
					start parameters and specifying a free UI port.
		else if some other command arrives:
			Reject it.

If the format of the Shutdown command changes, make sure the forked daemon can
	still handle it. This card should include adding the capability to receive
	fire-and-forget commands from a UI.

Reference GH-202.

**Comment by dnwiebe** [comment]
Suggested test plan (assuming you have `websocat` or Socket King or some other Websockets client installed on your system):

Start the Daemon, which is just the Node in `--initialization` mode. Look at the `--help`. Try various ways of starting it, and see if you can find behaviors that don't agree with the help, or don't make sense, or cause crashes. Since the Daemon isn't actually daemonized yet (there are three cards for that, one for each OS), when you start it it ought to block until you Ctrl-C out of it. The Daemon does not (currently) write to any log file, so whatever errors you can get it to produce should show up either as WebSockets responses or at the console (or both).

Here's the way the Daemon works:

1. After the Daemon is first started, and before it has started a Node, it's in Setup mode. In this mode, there are three things it can do:

a. It can accept a `setup` message containing zero or more name/value pairs, where the name is a command-line parameter for the service mode of the Node without the double hyphen (for example, `log-level`), and the value is the value of that parameter (for example, `trace`). It responds to the `setup` message by sending back a second `setup` message containing all of the name/value pairs that are currently prepared for use. (This means that an empty `setup` request can be used as a simple status query.)

The `setup` message looks like this:

```
{
    "opcode": "setup",
    "contextId": 1234,
    "payload": {
        "values": [
            {"name": "neighborhood-mode", "value": "zero-hop"},
            {"name": "log-level", "value": "trace"}
        ]
    }
}
```

b. It can accept a `start` message that directs it to start up the Node with whatever setup attributes are currently in effect, switch into Redirect mode, and send back a different `start` message containing the process ID and the UI port number of the newly-started Node.

The `start` request looks like this:

```
{
    "opcode": "start",
    "contextId": 1234,
    "payload": {}
}
```

The response looks like this:

```
{
    "opcode": "start",
    "contextId": 1234,
    "payload": {
        "newProcessId": 52743,
        "redirectUiPort": 12844
    }
}
```

c. It can accept any other properly-formatted UI message, intended for a Node rather than for the Daemon. When it does, it sends back a `redirect` message containing the error code 0x8000_0000_0000_0002 (`NODE_NOT_RUNNING`) and a string with a proper complaint.

```
{
    "opcode": "redirect",
    "error": {
        "code": 9223372036854775810,
        "message": "Cannot handle financials request: Node is not running"
    }
}
```

2. Once the Node has been started and the Daemon is in Redirect mode, it can do only two things:

a. It still accepts `setup` messages just as it did before. Currently, these Redirect-mode `setup` messages can change the setup state, just as Setup-state `setup` messages can. This behavior is not correct. It is expected for this card, but will be changed by a future card.

b. It can accept any other properly-formatted UI message, intended for a Node rather than for the Daemon. When it does, it sends back a `redirect` message containing the UI port on which the running Node is listening, the opcode of the incoming message, and the complete properly-escaped JSON text of the incoming message. The expectation is that code at a low level of the client will be listening for the `redirect` response, and if it is detected, the client will close its connection to the Daemon, use the returned port number to open another connection to the Node, re-send the original message, this time to the Node, and, if any response is received, route it back to the higher-level code of the client where the request originated, without the higher-level code being aware of the redirect.

```
{
    "opcode": "redirect",
    "payload": {
        "port": 23934,
        "opcode": "financials",
        "payloadJson": "<---escaped JSON here--->"
    }
}
```

Explore both Setup and Redirect modes using your WebSockets client and make sure all operations that should be successful are successful, and all operations that should not succeed report errors appropriately. Remember to check out what happens if you start the Daemon, then rename and replace the `MASQNode` executable with some other random executable that doesn't start up a Node, then send the running Daemon a `start` message. It should fail; but does it fail the right way?

3. In any mode, if you send a bad message to the Daemon, it should respond as follows:

a. If the message is so badly distorted that the Daemon can't tell what kind of message it is (if it's bad JSON syntax, or if the `"opcode"` and `"contextId"` fields are missing or of the wrong type) then the Daemon should respond with a message that looks like this:

```
{
    "opcode": "unmarshalError",
    "payload": {
        "message": <message explaining what's wrong>,
        "badData": <properly-escaped JSON from the bad message>
    }
}
```

b. If the message has valid `"opcode"` and `"contextId"` fields (but, for example, no `"payload"` field, or a `"payload"` field that's of the wrong type), you should get back a message with the same `"opcode"` and `"contextId"` fields, but an `"error"` field instead of a `"payload"` field with an error code (all the error messages of this type should contain the same error code) and a textual message telling what was wrong.

**Comment by dnwiebe** [comment]
Rejected. Defects found:

Items from --initialization command line that don't show up in the Daemon setup state:
--chain
--data-directory
--db-password
--real-user (except that this should never show up in Windows)

Items that show up in the Daemon setup state by default that shouldn't:
--ui-port

"redirect" response payload should have optional contextId field depending on whether what is being redirected has a contextId field or not

**Comment by Crazylegscrane** [comment]
MASQNode executable needs to be protected from overwriting.
