### ISSUE TITLE
--initialization mode should abort if not run in root or administrative mode

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#256]
Currently, the Daemon can be run in either privileged or unprivileged mode; but if it's unprivileged, it can't start the Node. Therefore, it should be modified to abort with an error message if it's not root (in Linux or macOS) or Administrator (in Windows).

**Comment by Crazylegscrane** [comment]
Test plan: Currently, the Daemon can be run in either privileged or unprivileged mode; but if it's unprivileged, it can't start the Node. 

Attempt to start the Daemon without privilege (sudo), ensure it fails to start and terminates immediately with a return message explaining why ( i.e. not privileged).

Also try  to access the node with masq setup or try starting the node with masq start. These should fail with an appropriate message explaining that the Daemon isn't running.

**Comment by dnwiebe** [comment]
This card got a little bigger in the meantime. Look at it this way:

A) There are two privilege levels: 
    1) high (Admin or root)
    2) low (standard)
B) There are five modes of operation for Node:
    1) Service mode (no mode parameters)
    2) Initialization mode (`--initialization`)
    3) DumpConfig mode (`--dump-config')
    4) GenerateWallet mode (`--generate-wallet`)
    5) RecoverWallet mode (`--recover-wallet')

When you put these together, that's ten things to try on each operating system--each of the five modes at each of the two privilege levels.

Service mode and Initialization mode require high privilege.
DumpConfig, GenerateWallet, and RecoverWallet can run at either privilege level, but are best at low privilege.

If you try to run a mode that needs high privilege in a low-privilege environment, you should get a polite message and an immediate abort--something like:

```
MASQNode in Initialization mode must run with root privilege; try sudo
```

If you run a mode that only needs low privilege in a high-privilege environment, you should get a polite message and then `MASQNode` should continue to run (possibly crashing and burning if you haven't provided all the right parameters, but the polite message is what this card is about). For example:

```
MASQNode in DumpConfig mode does not require root privilege; try without sudo next time
```
