### ISSUE TITLE
masq panic when Daemon is not running

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#263]
If `masq` is run when the Daemon isn't running, it panics ugly. It ought to gracefully terminate with an informative message instead.

**Comment by dnwiebe** [comment]
Note: Due to a slow-running CI sequence, the Windows build for this card isn't in MASQ-results yet. (Dan can get you one out-of-band if you need it.) Since this card contains nothing platform-dependent, we suggest you test the Linux and/or macOS versions while we work on speeding up the build.

Suggested test plan:

Open a command window. Conspicuously neglect to start up the Daemon. Run `masq` somehow--perhaps

```
$ masq setup
```

Observe that instead of a messy panic, it sedately supplies a sophisticated and informative and instructional error message and gracefully terminates.

That's it!

**Comment by Crazylegscrane** [comment]
Missing windows binaries to complete test.
