### ISSUE TITLE
Post-start setup state handling in Daemon

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#264]
Setup state is properly defaulted when Daemon comes up, but once a Node is started, it looks really weird. It probably ought to retain the settings used to start the Node and be immutable until the Node goes down.

**Comment by Crazylegscrane** [comment]
Initial thoughts on Test plan : 

Start Daemon in usual way with  --Initialization.

In second Terminal check the default Node setting are as expected with :  masq setup. 
Change  Node to zero-hop mode and start it up.

Check the setup output of the Node once live to a)ensure it is as instructed b) It is in a clear and readable manner as it was under Node terminal when setup was initially queried.

Can you change the setup of the live Node? or do you have to bring it down before you can change setup?
