### ISSUE TITLE
Chain/data-directory inconsistency

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#265]
When the Node is started with `chain=ropsten`, the logfile goes into ...`/mainnet/`...  That's probably wrong.  I need to figure that out and fix it.

Wait. Maybe it's the Daemon that always logs to mainnet.

The Daemon should log neither to mainnet nor to ropsten. The Node should always log to mainnet or ropsten (or dev or...I think there's one more) depending the parameters with which it was started.

**Comment by dnwiebe** [comment]
Defaulting is now different. The only parameter supplied by default by the Daemon is now `--dns-servers`. (This isn't intended to be a long-term situation; eventually, `--dns-servers` will be much more optional than it is now, and it'll default to whatever DNS server your system is using when the Node comes up.) Also, the `--ui-port` parameter is sent from the Daemon to the Node, but the `masq` command has no control over the value of it, so it's not displayed in the `masq setup` list anymore.

So...the way to test this is again to start up a Daemon (`--initialization`) in a window and run `masq` in another window.

First just do a `masq setup` to see what parameters will be sent. You should just see `dns-servers` with a value of `1.1.1.1`.

Now set `neighborhood-mode` to `zero-hop` so that you can start the Node without supplying a slew of other parameters. Remember that it's now `--neighborhood-mode zero-hop` rather than `neighborhood-mode=zero-hop`.

Start the Node with `masq start`, and watch the Daemon window to catch the startup logs from the Node. It should say where it's logging, and then print the Node descriptor, which will end with two colons, since you're in `zero-hop`. Look at the logging location: it should have ...`/mainnet/`... in it, since you didn't specify a different chain.

Now shut down the Node (`masq shutdown`) and change the chain. (`masq setup --chain ropsten`, perhaps.) Start up the Node again and make sure it's now logging for the new chain.

Shut it down again, change the chain to `mainnet`, start it up, and make sure it's logging properly.

And this is where my paltry developer's testing instinct ends. If you can think of other things to try, please try them.

**Comment by Crazylegscrane** [comment]
GH-265 Linux test:

masq setup display only dns value 1.1.1.1 👍

Once in zero hop,  and masq start the Daemon shows log in /mainnet/ with Node descriptor as expected.

On shutdown and changing the chain to ropsten and restarting node, the log changes to /ropsten/

Repeating this process several times all worked correctly.

I also changed the chain to " - - chain dev" which was accepted but the Node  crashed on startup. Initial output by the Daemon appeared to show the correct process for logs and descriptor but was followed by some output and crashed. I've never used "dev" before and maybe I shouldn't have.. But thought I should tell you.
