### ISSUE TITLE
Continue build-out of MASQNode-UIv2

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#325]
Need to add additional structure to allow messaging to be done over UI Gateway for:

check password
change password
generate wallets

Can be combined with GH-268

Rudimentary test plan:

Preparation:
Start up a Daemon and an interactive instance of `masq`. Type `setup --ip 1.2.3.4` (the actual IP address isn't important, but one has to be specified) into `masq`. Start up a file-explorer window pointed at the directory in which Node keeps its database. (On Linux, for example, that's /home/<username>/.local/share/MASQ/mainnet.) Delete the database (node-data.db).

Passwords:
Use the `start` command in `masq` to start a Node (and recreate the database). Now play with the `check-password`, `set-password`, and `change-password` commands. (If you don't know how to use them, try typing the command with a `--help` parameter.) You shouldn't be able to change the password when it doesn't exist; you shouldn't be able to set the password when it does exist; you should be able to change the password to whatever you like, unless you supply the wrong old password; and you should always be able to check the password, whether it exists or not. You shouldn't ever be able to remove an existing password (without deleting the database), although you may be able to change the password to "", which isn't the same thing. If you want to delete the database to start over, `shutdown` the Node first, and then `start` it back up afterward.

Also, whenever the database password is changed, the Node should send out a broadcast to all connected UIs (other than the one changing the password) notifying them that there has been a change. You can test this by opening one or two more command windows and starting interactive `masq` sessions in them too. Then set or change the database password from your original `masq` window and verify that you get notifications in your additional `masq` windows.

Wallet generation:
You shouldn't be able to use the `generate-wallets` command if the database already has wallet information. You shouldn't be able to use it if the database doesn't have a password set. If you can use it, it should generate and return wallet information--namely, a mnemonic phrase and two wallet addresses. Make sure you can use all the options (use `generate-wallets --help` to see them). You shouldn't be able to supply any erroneous information (for example, requesting a 10-word phrase, or supplying an invalid derivation path like 'booga'). If you supply the same derivation path for both consuming and earning wallets, you should get the same address back for both of them. If you're especially ambitious, you could use Ian Coleman's website to see if the mnemonic phrase plus the derivation paths produce the same wallet addresses there.

I'm sure there's plenty of other stuff I haven't thought of here; that's why I'm not a tester. Good luck!

**Comment by bertllll** [comment]
We have a couple of issues reported so far:

We have to decide whether to keep both commands: set-password and change-password
Because now both work if you supply only one parameter. I'm counting there number of parameters regardless which body of the command was used. It could change later according to the other issue.

We probably wrongly assumed that values for commands would be preceded by the parameters names. It would solve all edge cases, with no confusion. But that isn't true so we need to take care of that, probably that way as it is in setup command.

Another issue:
"It doesn't print across multiple interactive windows when I change the password. it prints a message to the daemon but not to the other interactive windows."
