### ISSUE TITLE
Find a suitable Protocol for Node

### ISSUE THREAD

**Issue by Crazylegscrane** [MASQ-Project/MASQ-Node-issues#344]
Find  a protocol or better yet, several of them that we can pretend to be using with high ports on both ends without attracting suspicion (Community job).

**Comment by Crazylegscrane** [comment]
Normally, if you use snooping software like WireShark to observe Internet traffic, you'll see TCP packets go by that have port numbers that follow a pattern.

Specifically, one of the port numbers will be a high value that was selected by the operating system, and the other port number will be some well-known low port (1024 or lower) on which the server being accessed is listening. For example, if the server is HTTP, the low port number will be 80. If the server is TLS, the port number will be 443. If it's telnet, 22...etc. So, TCP packets that look like this are perfectly normal:

From: xxx.xxx.xxx.xxx:42938
To:   yyy.yyy.yyy.yyy:80

From: yyy.yyy.yyy.yyy:443
To:   xxx.xxx.xxx.xxx:62938

Those are the sorts of TCP packets we'd like MASQ to be generating: the kind that don't raise any eyebrows.

But there's a potential problem.

Some ISPs want to charge you extra money if you run a server, because they figure you're running a business and therefore have more money to spend on your Internet connection. So if they see packets come through that look like this

From: <your IP address>:43209
To:   <unknown IP address>:443

From: <unknown IP address>:443
To:   <your IP address>:43209

they're fine with that, because they can see you're using a TLS Web server somewhere. But if they see packets that look like this

From: <your IP address>:80
To:   <unknown IP address>:59420

From: <unknown IP address>:59420
To:   <your IP address>:80

they'll kick up a fuss, because now it looks like somebody else is using an HTTP server at your IP address. They might delay such packets, or throw them away entirely, or send you a nasty email, or even simply jack up your rates to the business-service level. Or, if it's a government-controlled ISP in a country where running a server at a residential address is illegal, you might find police on your doorstep.

Right now, this is how MASQ will have to operate if it's going to masquerade data as HTTP or TLS. No one will believe that this packet contains TLS or HTTP data:

From: xxx.xxx.xxx.xxx:52954
To:   yyy.yyy.yyy.yyy:45793

TLS and HTTP connections are client/server connections, and neither of those port numbers looks like a server port. To believe data is TLS or HTTP, you'd want to see a server port like 80 or 443 or 8080 or 8443 or even 8081 or 8088 in there somewhere--something well-known, not a high port number above 40000.

People who live in areas where running a residential server means higher rates or angry police are caught in the middle here. They can't set up their Node to resemble a believable server because they'll get in trouble, and they can't set up their Node to _not_ resemble a believable server because it'll produce suspicious network traffic.

What we need is another protocol to masquerade as: some existing, fairly popular protocol that uses high ports on both ends. That would probably be some sort of peer-to-peer setup. Maybe some blockchain protocol, maybe a gaming protocol, maybe a peer-to-peer file-sharing protocol, whatever.

Find us a protocol--or better yet, several of them--that we can pretend to be using with high ports on both ends without attracting suspicion. It'd be perfect if the protocol commonly sent packets of widely varying sizes, and if the packet data was encrypted, so that eavesdroppers would be expecting to see long opaque passages of binary data without any particular structure.

Tasks:
 1) Pick us half a dozen of the protocols that would serve us best, put them in order of most valuable to least valuable.
 2) Write up a blurb on each of them including some links to documentation about how they work and explain why you picked them.

**Comment by kauri-hero** [comment]
handling in masqueraders milestone cards ;-)
