### ISSUE TITLE
Report logs to UIs - error reporting

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#349]
When the Node experiences non-fatal errors, it logs them to its logfile and continues operating. This is better than nothing, but it means that unless he understands where to look for the logfile and how to read it, the user will have no idea why certain operations aren't happening the way he expects them to.

Modify the Node so that whenever it writes a log of severity X or higher, that log is also broadcast to all connected UIs, so that they can display it to their users if they choose. The broadcast log should at least have level and text fields, so that the UI can treat logs of different levels differently. Breaking out the timestamp, thread, and source fields may at some point be useful as well.

Remember to implement all of this in `masq` as well.

Relates to error handling

Could possibly create another log level (poss in between INFO & WARNING) that can report useful info to the user (and any connected UIs)

**Comment by anonmate** [comment]
Would be brilliant to have:

Errors:
Warns:
Info:

We may implement functionality in regards to node if things go wrong (e.g an error is found). For example: 3 hop routing fails, we ask them if they want to select a new Entry Node ID (this seems to fix that issue most of the time - but this might just be a node bug)

**Comment by dnwiebe** [comment]
Rough sequence of development steps (I may accidentally leave out something important):

1. Add a UiXxxXxx message in `messages.rs` capable of carrying all the information you'll need in a log. Make sure all the fields are easily serializable as JSON. (For example, a field of type Level may not be, but a field of type String will be.) Make sure it's a `fire_and_forget_message` instead of a `conversation_message`.
2. Drive a match option into `BroadcastHandlerReal::handle_message_body()` to handle reception of a log broadcast. Perhaps you could use `ChangePasswordCommand::handle_broadcast()` as an example. Carefully design the way in which the log is displayed so that it doesn't unduly disrupt the user who might be in the middle of typing a command.
3. Modify `Logger::generic_log()` so that it can transmit logs to the UIGateway as well as sending them to the delegate logger. Careful here: you should not execute the expensive `log_function` that's passed to you unless the log should definitely be rendered, either for transmission to UIGateway or for sending to the log file. If it is executed, it should be executed only once per log. Make sure you test situations where the log is not rendered, where it's rendered only for UIGateway, where it's rendered only for the delegate logger, and where it's rendered for both. Use a test that can assert on how many times the `log_function` is called.
4. In the process of 3., it will be tempting to use a non-const static field to hold the Recipient for the UIGateway, and to access it unsafely. If you do this, be absolutely sure you're not ever going to get shared-memory contention between threads. If there's even a hint that you might, try another solution instead. Arc<Mutex<>> suggests itself, although locking a Mutex can be expensive.
5. Do a fair amount of manual testing, using `masq` while the Node sends it logs. Not only should you make sure the functionality isn't broken; you should get a user-experience feel for the interface, and come up with ideas for improving it if it turns out to be bad.

**Comment by dnwiebe** [comment]
Suggested pseudocode for controlling access to UIGateway Recipient for logging:
```

Data structure:

pub struct LogRecipient {
	guard: AtomicBool,
	recipient_opt: Option<Recipient<blah>>,
}

Data item:

static LOG_RECIPIENT: LogRecipient = LogRecipient {guard: AtomicBool::new(false), recipient_opt: None};

Log transmitter:

fn transmit_log (parameters) {
	if (LOG_RECIPIENT.guard.swap(false)) {
		// Transmit log to UIGateway if recipient_opt is populated
		LOG_RECIPIENT.guard.swap(true)
	}
}

ActorSystemFactory or delegate:

fn prepare_log_recipient (recipient: Recipient<blah>) {
	loop {
		if LOG_RECIPIENT.guard.swap(false) {
			LOG_RECIPIENT.recipient_opt = Some (recipient);
			LOG_RECIPIENT.guard.swap(true);
			break;
		}
		else {
			thread.sleep (Duration::from_millis (10)) // wait for the logger to finish
		}
	}
}
```

**Comment by bertllll** [comment]
**Test plan**

_Note from the beggining:
This test can be conducted only on the CLI version of our software._ 

You are supposed to run the Node as much as you want and observe if you can get and read occasional notifications.
Every log that is `Info`, `Warn` or `Error` should find a way to your UI, more precisely, to all UIs you have open.
It is desirable to run it the standard way, that is with the Daemon which will take care for you to start up the Node.
 
_Disclaimers:
Please keep in mind that if you use multiple UIs, and we actually want it, you need to initiate a proper connection to the Node with each of them. 
If you only start one additional UI and don't type any Node's command from there, while the Node is running, we cannot consider that UI connected (we say correctly that you haven't been redirected from the Daemon to the Node) and therefor you also should not expect to receive broadcasts.
However once your first request, sent from the certain UI, reaches the Node, the connection is established and broadcasts will start coming to your new UI automatically._

_Also it may seem strange and chaotic that every UI has to be busy with these considerably frequent messages.
I suppose that we will play a card later on that will allow to subscribe for broadcast only on a particular UI or we will be able to switch it on/off._
