### ISSUE TITLE
Rust compile error

### ISSUE THREAD

**Issue by Munchkin58** [MASQ-Project/MASQ-Node-issues#360]
**MASQ Node Version**
Need the full version of MASQ Node (e.g. MASQNode 0.4.2)
December 26 zip download. Unsure where to locate version number.

**Describe the bug**
Rust compile error

**To Reproduce**
1. Unzip download to /tmp
2. login as root "sudo bash"
3. cd /tmp/Node-master
4. run shell script ci/all.sh 

**Expected behavior**
Rust errors ----

src/stream_reader.rs: line 36
  let mut buf = [0u8; 0x010_000];
note: '-D clippy::unusual byte groupings' implied by -D warnings
help: consider: '0x0001_0000'

I corrected this to:
  let mut buf = [0u8; 0x0010_0000];

Then other errors appeared.

src/sub_lib/binary_traverser.rs: line 26
  pub fn next_bytes(&mut self, count: usize) -> Result<&[u8], ()> {

Note: '-D clippy::result-unit-err' implied by '-D warnings'
help: use a custom Error type instead

21 similar errors.  I stopped trying to correct them

**Screenshots**

**Log files**
Include any relevant logging information.

**Device Details (please complete the following information):**
 - Using Raspberry Pi 4b 8GB ram, Raspberry Pi OS Full (32 bit)

**Additional context**

**Comment by kauri-hero** [comment]
we have seen another user @humicro who has successfully compiled on different devices recently.

@Munchkin58 is this issue still current?
