### ISSUE TITLE
Log files are incorrectly placed under root directory

### ISSUE THREAD

**Issue by humicro** [MASQ-Project/MASQ-Node-issues#363]
**MASQ Node Version**
Compiled from latest commit.

**Describe the bug**
Log file is incorrectly placed under `/root/` directory.

**To Reproduce**
1. Log in as a regular user bearing sudo permission.
2. Run `sudo MASQNode --initialization`
2. It outputs `Log is written to /root/.local/share/MASQ/MASQNode_daemon_rCURRENT.log`
3. All log files are placed under `/root/.local/share/MASQ/`

**Expected behavior**
It shouldn't be logged in `/root/`.
It should be under `~/.local/share/MASQ/`, `/tmp/`, `/var/log/` or else.

**Screenshots**
None

**Log files**
`Log is written to /root/.local/share/MASQ/MASQNode_daemon_rCURRENT.log`

**Device Details (please complete the following information):**
 - Desktop
 - Ubuntu 20.04.Desktop 64-bit

**Additional context**
None

**Comment by kauri-hero** [comment]
Node is aimed at running in Linux with a non-root priviledged user - its aimed at Linux user 'sudo-ers'

If someone must run Node with root access, use the --real-user parameter defined

**Comment by czarte** [comment]
I tested this behavior on my Ubuntu VM and all seems to be correct. 

Here is the test with results:

Logged in as regular user "ubuntu" with sudo privileges.

command:
`sudo ./MASQNode --initialization&`

output:
```
ubuntu@masq:~/tests/generated/bin$ Log is written to /home/ubuntu/.local/share/MASQ/MASQNode_daemon_rCURRENT.log

          _____ ______  ________   ________   _______          Node Version: 0.7.3
        /   _  | _   /|/  __   /|/  ______/|/   __   /|        Database Schema Version: 9
       /  / /__///  / /  /|/  / /  /|_____|/  /|_/  / /        OS: linux
      /  / |__|//  / /  __   / /_____   /|/  / '/  / /         client_request_payload::MIGRATIONS (0.1)
     /  / /    /  / /  / /  / |_____/  / /  /__/  / /          client_response_payload::MIGRATIONS (0.1)
    /__/ /    /__/ /__/ /__/ /________/ /_____   / /           dns_resolve_failure::MIGRATIONS (0.1)
    |__|/     |__|/|__|/|__|/|________|/|____/__/ /            gossip::MIGRATIONS (0.1)
                                             |__|/             gossip_failure::MIGRATIONS (0.1)
                                                               node_record_inner::MIGRATIONS (0.1)


```

command:
`ubuntu@masq:~/tests/generated/bin$ ls /home/ubuntu/.local/share/MASQ`

outuput:
```
MASQNode_daemon_r00000.log.zip  MASQNode_daemon_r00001.log.zip  MASQNode_daemon_rCURRENT.log  polygon-mainnet
```

command:
`ubuntu@masq:~/tests/generated/bin$ ls /home/ubuntu/.local/share/MASQ/polygon-mainnet/`

output:
```
MASQNode_rCURRENT.log  node-data.db
```
