### ISSUE TITLE
MASQNode isn't able to recognize a relative path

### ISSUE THREAD

**Issue by humicro** [MASQ-Project/MASQ-Node-issues#365]
**MASQ Node Version**
Compiled from latest commit.

**Describe the bug**
MASQNode isn't able to recognize a relative path.

**To Reproduce**
1. Log in as a regular user bearing sudo permission.
2. Under user's home directory, run `sudo MASQNode --config-file .config/MASQ/config.toml`. It outputs:
```
Opened existing database at "node-data.db"
Problem with parameter config-file: Couldn't open configuration file "/node/.local/share/MASQ/mainnet/.config/MASQ/config.toml". Are you sure it exists?
Problem with parameter config-file: Couldn't open configuration file "/node/.local/share/MASQ/mainnet/.config/MASQ/config.toml". Are you sure it exists?
```
3. However, when an absolute path is provided, MASQNode is able to recognize it.
Run `sudo MASQNode --config-file ~/.config/MASQ/config.toml`. It outputs:
```
Log is written to /node/.local/share/MASQ/ropsten/MASQNode_rCURRENT.log
Opened existing database at "/node/.local/share/MASQ/ropsten/node-data.db"
```

**Expected behavior**
It should recognize the config file provided in both relative & absolute path.

**Screenshots**
None

**Log files**
None

**Device Details (please complete the following information):**
 - Desktop
 - Ubuntu 20.04.Desktop 64-bit

**Additional context**
None

**Comment by czarte** [comment]
This issue is corrected in card #731 with set of rules that needs to be followed when you using setting Node with config file. When you use naked path for config file e.g. `--config-file data_dir/config.toml`, you must specify the data-directory in command-line or environment.
