### ISSUE TITLE
Write and Deploy Server/Client for Automap Testing

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#373]
* Write and deploy a server somewhere on the Internet that will listen for a request from one of our port-forwarding tests and respond by initiating a TCP connection to the machine doing the test and sending an identifiable packet, perhaps containing the value of a field from the initial request.

* Modify the standard automapping test so that, using each available protocol, it sets up a small server, opens a hole in the firewall, orders a connection from the deployed Automap Server, verifies that the connection is made and the expected packet received over it, drops the connection, and closes the firewall hole.

**Comment by kauri-hero** [comment]
Hey @bertllll @dnwiebe 
We have work starting on an AWS account so we can deploy a small server for you to do this.
Will let you know directly when this is finished

**Comment by bertllll** [comment]
To how to test this card.

First I want to remark that this test maybe won't bring us just sweet fruits but maybe a lot of bitter juice too. 
We don't know if it is going to work in the way how the code for automap looks right now but we have no doubts that we need to know and find that out by testing. By this test, which will simulate a functionality, that is believed to become a part of the core product, in a situation similar to the eventual one. Hopefully this test will show us what we should look at next and what to do to get all finally working.

The test itself is quite plain; please download the binaries as usual and run `automap` with no additional parameters. Your router should have PCP, PMP or UPnP turned on (for case you remember that you disabled it before). 

Then you can tell us of what you saw printed on your screen or in your log (the log file is going to be created in the same directory with the executables).

We'll be happiest if the outcome speaks with words like "success" etc. but you should get a brief message also in other events, unfortunately, referring a failure.

Have fun...and have patience with us. :)

**Comment by bertllll** [comment]
To how to test this card.

First I want to remark that this test maybe won't bring us just sweet fruits but maybe a lot of bitter juice too.
We don't know if it's going to work in the way how the code for automap looks right now but we have no doubts that we need to know and find that out by some portion of testing. By this test, which will simulate a functionality, that is believed to become a part of the core product, in a situation similar to the eventual one. Hopefully this test will show us what we should look at next and what to do to get all finally working.

The test itself is quite plain; please download the binaries as usual and run `automap` with no additional parameters. Your router should have PCP, PMP or UPnP turned on (for case you remember that you disabled it before).

Then you can tell us of what you saw printed on your screen or in your log (the log file is going to be created in the same directory with the executables).

We'll be happiest if the outcome speaks with words like "success" etc. but you should get a brief message also in other events, unfortunately, referring a failure.

Have fun...and have patience with us. :)
