### ISSUE TITLE
Conflict due to using the default data directory if it contains a populated config file 

### ISSUE THREAD

**Issue by bertllll** [MASQ-Project/MASQ-Node-issues#380]
We should inspect which tests are sensitive on the fact that they accidently reach the directory where the configuration file is, including some conflicting values for the tests in it. Then we should redirect the home directory to the exclusive directory for the given test.

#### The way to solve that: 

Try to fill the config file with some possible values (being acceptable) and see how many tests fail because of that. Add an independent directory path to them, hardcoded just for the test.
(e.g. .param( "--data-directory", <no/problem/directory>) 
*EDIT: in some cases the issue resists to the easy way of solving it. For example for these unprivileged configurator_standard tests shown on the picture* 

<br/> <br/>

At least we should probably tune up these tests:

![image](https://user-images.githubusercontent.com/65427484/104207909-bebaab00-5430-11eb-81b4-49de6f72ba2e.png)

Whose failures were caused with this setting:
```
chain="ropsten"
ip="7.8.9.0"
clandestine-port="5678"
dns-servers="4.6.7.9"
gas-price="44"

**Comment by czarte** [comment]
As far as I understand this card, this behavior is correct. The order of overriding arguments for Configuration is:
1. config.toml - if user provide config.toml in data-directory and does not specify it in arguments (cmd or ENV) we are looking into data-directory, and if this directory contains config.toml, we read its content and set provided parameters to configuration.
2. ENV variables overriding config file parameters
3. Command-line arguments rewriting the parameters of config file and EVN.

In case we blanking previous arguments setted by ENV or command line, we are looking into layer below, and if this layer provides some of the blanked parameters, we are setting them up.

**Comment by czarte** [comment]
As far as I understand this card, this behavior is correct. The order of overriding arguments for Configuration is:

config.toml - if user provide config.toml in data-directory and does not specify it in arguments (cmd or ENV) we are looking into data-directory, and if this directory contains config.toml, we read its content and set provided parameters to configuration.
ENV variables overriding config file parameters
Command-line arguments rewriting the parameters of config file and EVN.
In case we blanking previous arguments setted by ENV or command line, we are looking into layer below, and if this layer provides some of the blanked parameters, we are setting them up.
