### ISSUE TITLE
Overhaul the main README.md

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#382]
It's been a long time since the README was checked. The Daemon and `masq` have come into existence since then.

Review the README and bring it up to date. Maybe add some pedagogical images.

**Comment by dnwiebe** [comment]
Test plan:

Check the following files for inaccuracies, clumsy language, unclear explanations, bad filenames, and so forth:
https://github.com/MASQ-Project/Node/blob/master/CODE-OF-CONDUCT.md
https://github.com/MASQ-Project/Node/blob/master/COLUMNS.md
https://github.com/MASQ-Project/Node/blob/master/CONTRIBUTING.md
https://github.com/MASQ-Project/Node/blob/master/PRACTICE.md
https://github.com/MASQ-Project/Node/blob/master/README.md
https://github.com/MASQ-Project/Node/blob/master/USER-INTERFACE-INTERFACE.md
https://github.com/MASQ-Project/Node/blob/master/node/docs/PORT_53.md
https://github.com/MASQ-Project/Node/blob/master/node/docs/Blockchain-Service.md
https://github.com/MASQ-Project/Node/blob/master/node/README.md
https://github.com/MASQ-Project/Node/blob/master/node/src/sub_lib/README.md
https://github.com/MASQ-Project/Node/blob/master/node/src/proxy_server/README.md
https://github.com/MASQ-Project/Node/blob/master/node/src/test_utils/README.md
https://github.com/MASQ-Project/Node/blob/master/node/src/ui_gateway/README.md
https://github.com/MASQ-Project/Node/blob/master/node/src/accountant/README.md
https://github.com/MASQ-Project/Node/blob/master/node/src/proxy_client/README.md
https://github.com/MASQ-Project/Node/blob/master/node/src/entry_dns/README.md
https://github.com/MASQ-Project/Node/blob/master/node/src/hopper/README.md
https://github.com/MASQ-Project/Node/blob/master/node/src/neighborhood/README.md
https://github.com/MASQ-Project/Node/blob/master/multinode_integration_tests/tests/README.md

**Comment by kauri-hero** [comment]
I have created branch gh-382rev2 to cover any immediate changes needed to cover Polygon network inclusion and cleaning up other historical changes
