### ISSUE TITLE
Make Database Picky About Chain

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#401]
A particular database is only useful on a particular blockchain. Add a chain-id identifier to the CONFIG table of the database, and put in code that will crash at startup if the Node is pointing at a database that was created for a chain different from the chain currently in use.

**Test plan** / Bert

I'm going to lead you to focusing on one aspect of this card that is more important to others. The rest will depend on your consideration.

But before I get to the point, I certainly welcome everybody not opposed to trying out even what is optional. This involves trying to witness an update of your old database at the first go you run the newly downloaded binaries for this card. If you look carefully you'll be able to see information that your database has been successfully updated exactly as it happened last time we tested something very similar to this; just look into your node's log file after you have successfully started up your Node. (There were some muddle when we tried to find the right log file to look into last time so I'm leaving it up to you if you want to try again with this card now.). Just for completeness, if you do you should see 'INFO: DbMigrator: Database successfully updated from version 1 to 2" 

Here we come to the compulsory part of this test. Please use the database file which you can find attached here below. It is quite a normal database, the only specialty this involve is that it contains value 'renkiby' in place for 'chain_name' parameter. That means that if you take this file and replace your database (attention here) from your 'mainnet' folder with it you will cause that you will have a database which doesn't belong in there because it should be 'mainnet' what to be found in the row, yet there is 'rinkeby' now. Next you should attempt to start up your Node the normal way, as you're used to. Just make sure that you don't touch the parameter with the desired 'chain'. Put a bit better, ensure yourself that 'chain' is either 'default' (meaning 'mainnet') or you have to set it to 'mainnet' manually to proceed smoothly through this test. The expected result is to see your Node panic (in other words 'stop to work and free its resources given by the OS'.) for the reason that we detected during its start-up that it pointed to a wrong database. 

If you turn your attention to the log file of the Node now, you can also see a message that tries to make the reason of the sudden panic more obvious for people from outside. For now and also future reference, always look for the last lines there which so far tend to look linear and neaten, the part starting afterwards is called backtrace and it informs a programmer being interested about what function calls went before but also after the moment of the panic. But again, if there is any message produced during the panic, which you may want to see, then you'll read it from the few lines before the chaotic backtrace unwinded later. 

[node-data-modified.tar.gz](https://github.com/MASQ-Project/Node-issues/files/7072216/node-data-modified.tar.gz)

**Comment by Crazylegscrane** [comment]
In addition to the information and plan found here https://github.com/MASQ-Project/Node-issues/issues/401 I have some further notes which may speed up your process for testing and save you some trouble. You would probably figure these out yourself anyway:

The first part of GH-401 concerns the "optional" but not optional to me part about the updating of the database (you should remember this from a previous card). We have sometimes in the past wiped our databases for various reason, but on this card you should not. You will need an "older" database file in order for it to be updated and present you with the confirmation. If you do not have an old database, you can simply take an older set of binaries and setup and run the basic Node to create a database. Once you have this older database you can then shut it all down, download the new binaries for GH-401 and proceed.

The second part of the plan requires you to use the node-data-modified.tar.gz at the bottom of the test plan. When you replace the database with this downloaded version you will need to change the name of it to simply-     node-data     and all should be good. I hope that helps you and as ever... thanks.

**Comment by kauri-hero** [comment]
I believe this was passed in QA under Windows, Mac and Linux

I just wanted to check we can move this to Done? @bertllll @dnwiebe

**Comment by bertllll** [comment]
No review has been done; that's why it got stuck. @kauri-hero

**Comment by kauri-hero** [comment]
ok we should get someone to review this ASAP.

Maybe @masqrauder has capacity please?
