### ISSUE TITLE
Document for the testers' community

### ISSUE THREAD

**Issue by bertllll** [MASQ-Project/MASQ-Node-issues#404]
We discussed with Stew that it might be helpful to provide a list of commands (with their help copied probably) and assurance that the information is up to date. 

So we could also go through all the help text looking for if anything underwent changes.

Explore the idea of having a build-sequence program that would run `masq --help` and dump the result into a Markdown file in the codebase. Then that Markdown file could be referenced in @kauri-hero 's Git Book.

@Crazylegscrane

**Comment by kauri-hero** [comment]
this is a good one, and hopefully at same time we can collate this and update our https://testing.masq.ai Gitbook to reflect this for any testers in the public
