### ISSUE TITLE
Change the default for mnemonic phrase length

### ISSUE THREAD

**Issue by bertllll** [MASQ-Project/MASQ-Node-issues#414]
As for the mnemonic phrase, our fellow workers from GUI chat came to consensus that 12 is a better default value instead of 24, which is a value that, of course, should stay optional. 

Recommendation: maybe ask our colleagues in the chats or somewhere to ensure that this is still the desired direction to go; this card is quite old and preferences may change with time.

**Comment by anonmate** [comment]
@bertllll Do I remember you saying you had already done this? @kauri-hero Would be great to get this in ASAP if it's a quick change for the new GUI development that will start next week

**Comment by kauri-hero** [comment]
Thanks @anonmate 
I've pinged @bertllll to see if this was changed.
Not sure if the default is still 24

**Comment by bertllll** [comment]
Hello @anonmate, I have to disappoint you. This change is just on the paper at the moment. 
Would it be quick enough for you if I provided the new version during this Monday?
Maybe there will be a quick test required though. 
@kauri-hero @Crazylegscrane  What do you think? What can we do about testing to make the process smooth.

**Comment by bertllll** [comment]
Oh. I just realized something. @anonmate You don't have to care about this, because the Node doesn't contain any information about the default value for mnemonic phrase length. We do have it, but it's only an attribute of our CLI UI. 

So I think you have no obstacles to design your code with your preferences in it regardless us. The Node is ready to accept any word count from the range of 12, 15, 18, 21, 24. And I will play this card, which is in fact strictly CLI dependent, some day in the future. 

Contact me if it won't work.

**Comment by kauri-hero** [comment]
thanks @bertllll that makes perfect sense.
The GUI can just prompt users to pick the amount we decide on from the options. (12 seems to be common choice)

We could consider an 'advanced' tab that lets users choose 24 if they wish @anonmate ?

**Comment by FinsaasGH** [comment]
The default length has been changed from 24 to 12.

**Comment by FinsaasGH** [comment]
Test plan:

Goals:
- Check in GUI/CLI if default phrase length is 12
- Check in GUI/CLI if values 15,18,21,24 still work
- Check if wallets generated via GUI/CLI are correct – via Ian Colemans site
- Check if wallets generated can be recovered correctly

Binaries:
MacOS - [MacOS GH-414 Binaries](https://github.com/MASQ-Project/Node/suites/3909787314/artifacts/97665392)
Ubuntu - [Ubuntu GH-414 Binaries](https://github.com/MASQ-Project/Node/suites/3909787314/artifacts/97665393)
Windows - [Windows GH-414 Binaries](https://github.com/MASQ-Project/Node/suites/3909787314/artifacts/97665394)

Steps:

Generate Wallets:
1. Ensure old DB is deleted
2. Start the Daemon
3. Start the node
4. Run `set-password`
5. Run `generate-wallets`
6. Copy the mnemonic phrase and addresses generated into a text editor

Verify Wallets:
1. In your browser window, go to Ian Coleman's web page [https://iancoleman.online/](https://iancoleman.online/) to recover wallet using the mnemonic phrase used
2. Enter the mnemonic phrase into "BIP39 Mnemonic" field
3. Change Coin field to ETH
4. Click Generate
5. Scroll down and verify consuming address and earning address vs recorded earlier by generate-wallets

Recover Wallets:
1. Stop Node/Daemon
2. Delete database
3. Start Daemon/Node
4. Run `set-password`
5. Run `recover-wallets`
6. Run `wallet-addresses`
7. Verify addresses vs recorded earlier by generate-wallets and from Ian Coleman website

Repeat setup using GUI and verify wallets as before.

For extra points: try adding `--word-count` to `generate-wallets` and repeat the steps for each possible value (12,15,18,21,24)

**Comment by kauri-hero** [comment]
will add this to the QA workflow soon
