### ISSUE TITLE
Research Note - consider future proof of Websockets for an Electron based GUI - using IPC instead of Websockets

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#420]
Great for UI & node communication

https://nickolinger.com/blog/electron-interprocess-communication

https://www.scriptol.com/javascript/ipc-vs-websocket.php

Suggestion from Microoo

**Comment by dnwiebe** [comment]
Recommendation: no.

Objection #1: IPC is much more platform-dependent than WebSockets. Especially now that we're a volunteer group where some or most developers have access to only one kind of platform, platform-dependent code should be avoided.

Objection #2: WebSockets is not liable to go away anytime soon. Even if it did, we control both ends of the connection, so we could continue using it. TCP would also have to go away to cause us trouble, and that's unlikely to happen.

Objection #3: We already have the interface working just fine in WebSockets, and given that IPC is less desirable and that WebSockets is not obsolescent, the value of investing a lot of dev work to do the switch is unclear.

**Comment by kauri-hero** [comment]
Thanks for your insight on this @dnwiebe 

I do agree with your recommendation after further review.
I will flag this as a 'won't fix' tag and close this card.
