### ISSUE TITLE
Node fails to compile on M1 Macs

### ISSUE THREAD

**Issue by markmunoz** [MASQ-Project/MASQ-Node-issues#425]
**MASQ Node Version**
Building from master branch sometime after 0.4.8 assumedly?

**Describe the bug**
Trying to compile and build the Node on a M1 Mac will fail with an error about INODE64 being referenced.

**To Reproduce**
1. Clone Master on an M1 Mac
2. brew install rustup
3. rustup-init
4. ci/all.sh

**Expected behavior**
Hopefully a clean build with no errors

**Log files**
note: Undefined symbols for architecture arm64:
            "_statfs$INODE64", referenced from:
                core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$mut$u20$F$GT$::call_once::hc51b1f37d692b7bf in libsysinfo-0bb98a18c1893cfc.rlib(sysinfo-0bb98a18c1893cfc.sysinfo.acj45gfk-cgu.8.rcgu.o)
                _$LT$sysinfo..mac..disk..Disk$u20$as$u20$sysinfo..traits..DiskExt$GT$::refresh::h37c3c42bdf056731 in libsysinfo-0bb98a18c1893cfc.rlib(sysinfo-0bb98a18c1893cfc.sysinfo.acj45gfk-cgu.8.rcgu.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Device Details (please complete the following information):**
 - Device Type M1 Mac mini
 - OS name and version Mac OS 11.2.2

**Additional context**
Electron had a similar bug with a dependency they used this was the PR that closed the issue.  https://github.com/al45tair/mac_alias/issues/10

**Comment by anonmate** [comment]
@markmunoz Wasn't this fixed by updating Rust version?
