### ISSUE TITLE
Remove dead parameter-processing code

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#457]
Back before we had `masq`, certain command-line parameters allowed back-and-forth interactivity: for example, if `--db-password` was specified without any value, `MASQNode` would prompt the user for a password without echoing it.

That functionality is now taken over by `masq` and other UIs; therefore the code that implements it is dead and should be removed.

Caution: do _not_ remove tests for this code without removing the code under those tests; that will result in code that is both dead _and_ untested.

**Comment by bertllll** [comment]
What Dan talks about up here takes place in src/node_configurator/mod.rs (mostly, if not only).
