### ISSUE TITLE
New system of employing chains regarding the expansion to L2 networks

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#473]
```
Implement changes to descriptor format and use of a clear identifier that allows users and Nodes to connect and gossip around the correct network.

Need to designate a network identifier and then further, a designator for testnet or mainnet

Also inspect the single character array for network choice within the code

Current descriptor format
descriptor - separator - ip : port

currently colon ':' is for testnet
'@' for ethereum mainnet

Polygon Mainnet:
human readable - mumbai
Idea - prefix hex value - $ ip : port

Polygon Mumbai testnet
human readable - mumbai
Idea - prefix hex value - : ip : port

IDEA:
descriptor $POLY @ ip:port
descriptor $ETH @ ip:port

Need to reference what delimiter the current testnets of Ropsten and Rinkeby are using

Also need to consider the software and error handling for someone using incompatible descriptor for another network
```
The previous was just a small part in the end and I had to extend.

The changes cover this:

- descriptor remodelation and a new parsing apparatus within Node plus the multinode area 
-declination from usage of a simple numeral chain_id, it's replaced by a full data chain offering a reference to where we can query any parameter of the chain; it's a big step for the future; it drove in changes for the whole codebase
- addition of two new chains for Polygon: the mainnet and the testnet Mumbai, including all their data in their records
- update of contract_creation_block_numbers to the values appropriate to MASQ
- simplification of the offer of constants reffering to chains for both test and real use situations, from many we now have just two instead of many like in the past. All required data can be fetched and read based on these two constants in the code.
- removal of Rinkeby 
- signing transactions now accepts very high ID numbers - it turned out that we have to fix signing for Polygon and now we know how to do that but it will be done in a different card
- clearance in the way of using the dev chain, where it should exist only within the space of multinode tests

**Comment by bertllll** [comment]
**Test plan:**

This is a huge bite that may look subtle at first. Let's not get fooled, brothers in arm. Here I'm providing a number of points that might be worth checking. 

Despite this is a factual preparation which will end by enabling a multichain solution, at this moment, only the old fellows (that is Ethereum chains) are made available; anyway, you'll meet them in a new coat now. I'll come with another card that will add new chains (probably Polygon?) after this one.

- it may be smart to begin with reading the help text for both `MASQNode --help` and `masq setup --help`, it will give you a picture of what the new look of our descriptors is like. Remember that these help options are under the scope of the test as well as anything else, so have your comments on it if you want. Feel free to correct my English. 

- you should certainly try to run the Node with use of the new descriptors. You can take some old ones which were used in the networking tests e.g. and rewrite them into the newer form. If nothing else It'd give you some practice on them.
- it may be a good idea to try all four versions of "public chains" (chains provided to the public) which are Polygon mainnet, Polygon Mumbai, Ethereum mainnet, Ropsten. You can see no mention of Rinkeby, well, Rinkeby's been finally removed for not having been used. If you want to you can also manipulate with our private chain 'dev' but this one for example shouldn't work for transactions. It is important though to assert that the Node also knows the lastly mentioned chain and accepts this option as easy as the other options.   
- what is quite important I want you to check is what happens with your data directory when you use this version. The difference lies in that I had to make some distinguishing for ETH mainnet and POLYGON mainnet which led to a new middle folder in the data storage structure. It's going to be in either 'eth' or 'polygon' folder where you should then see 'mainnet' and 'ropsten' inside, similarly as you've been used to, or 'mainnet', 'mumbai' as for the polygon alternative. Please check these all. To see these to be created and exist you will need to start the Node with all four chains singularly set, one a time. It will make the Node create them. 
It may be confusing that your Node will create them in the same space where you already have your old folders. Well, should be nothing but confusing, if you know what's going on, it shouldn't harms us. At a normal time, it will look differently when the testing process is not going.   
- I think you should "accidentally" send in a badly formatted string to see what error messages you may get. Analyze the error messages to decide if they are adequate.
- don't forget please to test out the `descriptor` command (remember - Node must be running at the moment)    

Blessings on your hunt!

**Comment by bertllll** [comment]
Just for completeness:
I came to a decision to merge this back with GH-488 which is gone now. It wasn't the luckiest one but I had to do it to make the review considerably easier. 

The next text was just brought over here from the other card. No too big importance.   
```
I'm going to merge this card with tasks from GH-475 because these things have much in common.

Copied from the other card's description. Created by Kauri.

Add token addresses to support the Polygon layer tokens within the code.

Polygon Mainnet
MATIC:
0x0000000000000000000000000000000000001010
MASQ: 0xEe9A352F6aAc4aF1A5B9f467F6a93E0ffBe9Dd35

Polygon Mumbai Testnet
MATIC:
0x0000000000000000000000000000000000001010
Shroud: 0x4DFEEe01f17e23632B15851717b811720Af82E0f

@bertllll - i've added the blockheights for default values

Blockheights

MASQ POLY mainnet - 14863650
MASQ POLY mumbai testnet - 18750537
MASQ ETH mainnet - 11170708
MASQ ETH Ropsten testnet - 8688171

@bertllll
Member Author
bertllll commented 2 days ago •

I'm also going to fulfill the work of GH-480 in this card instead...it was about investigating what is and should further be the default for chains if nothing more is said as for configuration.

We agreed with Kauri that for this moment we'll continue with end-user default to be "eth-mainnet", though it's very likely to change to "poly-mainnet" later.
Regarding the developers' side, we'll probably continue to use ropsten as a chain of first choice for testing (just intern purposes).
```

**Comment by kauri-hero** [comment]
thanks @bertllll I was looking for this text for sometime LOL
I was having trouble finding it in my notes.

I'm glad you created this comment and merged the card back over, because this will provide the completeness of this card

Feel free to label some of the cards as 'wontfix' if they are now encompassed in the spirit of this card itself!
