### ISSUE TITLE
Database creation for L2 solution

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#474]
Accounting is kept track of in the database, so an identifier would need to be referenced to create/use correct network, especially if the network hasn't been used by the user before
(eg connecting to the Polygon MASQ Network after connecting to ethereum mainnet)

Consider the pathway for user to run Node on another network, and use existing configuration from an existing database

After discussion with @masqrauder , there may be a need for double mapping for the chain index (currently an array)

**Comment by dnwiebe** [comment]
If the idea here is that the user could run the same Node on several different networks, either simultaneously or serially, this is a massive change, and should probably be an epic on its own.

If the idea here is that the user could have a database for each network, and bring up his Node on whatever network he likes, and have it stay on that network and never touch any other networks, this is pretty easy and may already be done.

**Comment by kauri-hero** [comment]
The latter is the approach we are after.At this time we don't want a cross blockchain network interaction. The intent is that there is a user database for each network and once the user brings up his/her node, it will remain on that network for consistent use 😉
