### ISSUE TITLE
Chain ID change for references to different chains

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#479]
Currently there is an array used for the chain ID value, to reference the various chains, and this provides a reference for the token contract and blockchain

Consider removing the rinkeby chain as its never used.
Currently 1 is eth
2 is dev
3 is ropsten
4 rinkeby

While work done on this card, explore removing rinkeby as it is never used

Need to add polygon and mumbai chain IDs and the name reference to go along with them, which will allow the correct reference to token contract and database

**Comment by kauri-hero** [comment]
This has been completed in the work done on GH-473

**Comment by anonmate** [comment]
@kauri-hero Should this be closed?

**Comment by kauri-hero** [comment]
> @kauri-hero Should this be closed?

Thanks mate - yes its in the DONE column I believe, so its considered complete.

We will close a number of these soon officially ;-)
