### ISSUE TITLE
EMERGENCY - Windows test/action race condition

### ISSUE THREAD

**Issue by FinsaasGH** [MASQ-Project/MASQ-Node-issues#483]
handles_startup_and_shutdown_integration fails in actions but passes locally. 

[actions_log.txt](https://github.com/MASQ-Project/Node-issues/files/7218812/actions_log.txt)
[local_vs_actions.txt](https://github.com/MASQ-Project/Node-issues/files/7218815/local_vs_actions.txt)

Test was commented out for windows to allow builds to succeed.

This will be backlogged for when it can be inspected again, during Actions builds

**Comment by bertllll** [comment]
I don't think we are still getting this test failure in Actions. I barely remember the history, I just know something was tried or even done successfully to make this trouble-making guy politer. I'm not sure though. Speaking just for me with my own experience.
