### ISSUE TITLE
Command to output node descriptor

### ISSUE THREAD

**Issue by markmunoz** [MASQ-Project/MASQ-Node-issues#486]
During automation of a cloud node it would be super useful to have a MASQNode or masq cli binary command that would output the current node descriptor.  With this functionality I could set the output of that command to an ENV var and use it to further call API's about what cloud node API's are online, but I could also have a script for when a machine is doing a graceful shutdown it removes itself from the node API servers as well.

**Comment by kauri-hero** [comment]
hey @markmunoz 
We did handle this with a websockets message `descriptor` which responds to the UI with the descriptor value

this is able to be used on a running node, and I have tested it from command line, using the `descriptor` command from the masq UI process.

![image](https://user-images.githubusercontent.com/55721017/140632562-a0ec07b6-1f48-4121-a12e-a48eaa2167dd.png)

this should continue to be supported with the new descriptor format in GH-473
