### ISSUE TITLE
Windows: Missing VCRuntime.Dll will throw error -> no descriptor is generated

### ISSUE THREAD

**Issue by clandest** [MASQ-Project/MASQ-Node-issues#49]
**SubstratumNode 0.4.8**

**Describe the bug**
Missing VCRuntime.Dll in windows will give error and descriptor won't be generated

**To Reproduce**
1. Delete VCRuntime.dll or uninstall Microsoft Visual C++ 2015 redistributable update 3 RC
2. Start node 
3. Hit serve
4. Paste descriptor
5. Hit start

**Expected behavior**
Descriptor gets generated after hitting start

**Screenshots**

**Log files**

**Device Details (please complete the following information):**
 Win10x64

 - Application [e.g. chrome, safari]

**Additional context**
Microsoft Visual C++ 2015 redistributable update 3 RC the problem is fixed. Suggest including VCRuntime.dll in installer.

**Comment by kauri-hero** [comment]
I believe Steve had resolved this for Windows users at some point between RC2 and RC3
