### ISSUE TITLE
UI messaging for financials

### ISSUE THREAD

**Issue by anonmate** [MASQ-Project/MASQ-Node-issues#493]
The GUI team needs UI messaging so we can know the following financial information from the accountant:

- MASQ Incoming estimated
- MASQ Incoming confirmed total

- MASQ Outgoing pending
- MASQ Outgoing confirmed totals

This relates to GUI issue:
https://github.com/MASQ-Project/MASQ-React-App/issues/91

**Comment by kauri-hero** [comment]
combined into #236
