### ISSUE TITLE
IP Address Change Handling

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#499]
GH-372 intended to make the Node sensitive to IP changes, among other things. The other things worked, but IP change detection proved to be enough of a problem that it was withdrawn from GH-372 to get the rest of the functionality out.

The purpose of this card is to reinstate the IP change detection and get it right.

For PCP and PMP, the issue involves correctly combining UDP multicast reception with SO_REUSEADDR and SO_REUSEPORT flags (and the equivalent in Windows). 

For IGDP, the lack of IP-change detection in the `igd` library means we either A) must regularly poll for IP changes, as GH-372 already does, or B) use a different library (whether locally written or not) that _can_ handle IP-change detection.

Automated testing remains a problem, for three reasons. First, no single installation will have hardware for testing PCP, PMP, and IGDP. Second, ISPs cannot be depended on to change one's IP address on demand. Third, unit testing is limited, since the host-wide nature of UDP multicasting means that it's difficult to send multicast messages from one process or thread to another on the same host. Possibly this indicates that real testing will need to employ `multinode_integration_tests`.

**Comment by dnwiebe** [comment]
Note: This card has been split up into GH-527 - GH-532. Don't play this card; play those cards.

**Comment by kauri-hero** [comment]
done in #531
