### ISSUE TITLE
Add a release/debug function for packages to appear on our GitHub

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#522]
replaced by card #589 

Currently there are fundamental project needs to have more robust gitflow and release of stable binaries, separated from other development and feature branch workflows in GH Actions

Requirements:
Use GitHub releases and tags to ensure that desirable Actions builds produce binaries that can be fetched into other CICD automations.

This will likely require an interim branch to be considered (eg `dev`)

Research the ability of GitHub Releases to perform this, and any requirements for the `master` branch in terms of changing the ci-matrix and/or a release

https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

**Comment by bertllll** [comment]
This may be correlated with #91. 

I don't understand exactly the intentions behind the introducing words here, maybe it should be extended @kauri-hero 
Also, I want to say that although it's of different scope I'd appreciate if we even could smuggle the Node's version (if we've invented some versioning) into the log file as information printed on the first line. We could then see which Node's version log file we're analyzing.

**Comment by kauri-hero** [comment]
@FinsaasGH I've linked this article into the Card description
https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

Also we need to look into rolling back all the automated versioning that displays v1.0.0 everywhere in the code, since we will have to start with a minor version
