### ISSUE TITLE
499: Design IP change Gossip modifications

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#529]
When a Node has its IP address changed, it needs to inform its neighbors of that change, mostly because those neighbors need to know where to tell new Nodes to contact it in Introduction and Pass Gossip.

The Node whose IP address has changed needs to send a (probably as-yet-nonexistent) Gossip message to its neighbors that does at least the following:

* Contains its new IP address
* Contains its old IP address
* Proves cryptographically that the same computer that was at the old IP address is now at the new IP address. (Suggestion: sign or encrypt the neighbor's public key.)

The Node that receives an IP-change Gossip message must at least:

* Verify whatever proofs are provided and do the appropriate banning if they fail
* Kill all existing TCP connections to the Node whose IP has changed
* Reestablish those TCP connections to the new IP address. Note that either Node in the relationship (not both) may be originate-only or consume-only Nodes, and hence not be able to receive connection attempts; design the protocol so that the replacement connection(s) can be established in either direction. Keep in mind that each NeighborhoodDatabase includes NodeRecords with `accepts_connections` flags in them, so both sides will know if one side or the other can't accept connections.

No code is necessary to complete this spike; just design the protocol changes and make sure they'll work.

**Comment by kauri-hero** [comment]
done in #531
