### ISSUE TITLE
Provide default values for Node for testnet

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#550]
_This was discussed with @bertllll and default values for testing will be coded into MASQ-Project/Node#382 for now.
It is expected that for mainnet launch a new set of tested defaults will be updated in the code_

For upcoming testnet (and mainnet) we will need to hardcode various default values to ensure clean UX and also minimize known issues that could exist with network dynamics.

While doing this card, it may be considered to have chain-specific defaults - but will need to check with @bertllll on the added complexity this may created to the card itself.

default values should include (but not limited to) the parameters :
`chain` = polygon-mumbai
`gas-price` = 30

**RatePack**
| Rate Parameter | value |
| --- | --- |
| routing_byte_rate | 1 |
| routing_service_rate | 100 |
| exit_byte_rate | 3 |
| exit_service_rate | 300 |

**Payment Curves**
| Curve Parameter | value |
| --- | --- |
| payment_suggested_after_sec: |  1200 |
| payment_grace_before_ban_sec:  | 1200 |
| permanent_debt_allowed_gwub:  | 500000000 |
| balance_to_decrease_from_gwub: | 10000000000 |
| balance_decreases_for_sec: | 2592000 |
|unban_when_balance_below_gwub: | 500000000 |

**Comment by kauri-hero** [comment]
@bertllll could you please look into the current default value for `log-level` please?

**Comment by bertllll** [comment]
@kauri-hero 
Sorry, I hadn't noticed of your question until now...and also by chance. 
The default for log-level is `warn`.

But I'd like to ask you what you think of the hypothetical modification towards chain specific defaults? What thing would it try to solve?
When it comes to feasibility, it seems to be doable without big hassle.    

Only Daemon recognize phrases like that a certain value is defaulted. Node doesn't care, it takes value from the database without knowing if it is default. 
So the change would require just small changes in setup_reporter.rs.

I'm saying that if you have sympathy or better said some indication for multiple defaults for the same parameter please tell me before I start this card. I think I should do after MASQ-Project/Node#382, right?

**Comment by bertllll** [comment]
@kauri-hero 
Also aren't the values somehow off normal measures?
For example permanent_debt_allowed is 500000000 of Gwei in MASQ which is the same as half a single MASQ, isn't it?
That would bring you into troubles with bans very soon or how much data can you request by your calculations for 0.5 MASQ?

**Comment by kauri-hero** [comment]
> But I'd like to ask you what you think of the hypothetical modification towards chain specific defaults? What thing would it try to solve? When it comes to feasibility, it seems to be doable without big hassle.
> 
> Only Daemon recognize phrases like that a certain value is defaulted. Node doesn't care, it takes value from the database without knowing if it is default. So the change would require just small changes in setup_reporter.rs.
> 
> I'm saying that if you have sympathy or better said some indication for multiple defaults for the same parameter please tell me before I start this card. I think I should do after [GH-485](https://github.com/MASQ-Project/Node-issues/issues/485), right?

To be honest, its really just been around the `gas-price` parameter which greatly differs from eth and polygon chains.
But I forsee us moving towards using blockchain calls such as eth_estimateGas to inspect if gas pricing is appropriately priced with the network conditions, and maybe look towards that a little more.
But as it stands, a user can simply put gas-price=40 on polygon and probably never have any gas issues

I would say this is definitely a separate card though (for chain specific) and I will change this card to outline that.
certainly something to do after MASQ-Project/Node#382
@bertllll

**Comment by kauri-hero** [comment]
> @kauri-hero Also aren't the values somehow off normal measures? For example permanent_debt_allowed is 500000000 of Gwei in MASQ which is the same as half a single MASQ, isn't it? That would bring you into troubles with bans very soon or how much data can you request by your calculations for 0.5 MASQ?

I believe with the estimates this should be fine and not result in bans.
It would require a lot of consuming traffic to rack that up within a scan timing of 20 minutes
