### ISSUE TITLE
Tests for constants

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#569]
*Could this be a suitable card for @utkarshg6  ??*

Most, if not all, of the constants in our code are untested.

This means that there's a danger that some developer may accidentally change the numeric (or string) value of a constant without realizing it, by a mechanism as simple as fat-fingering, or perhaps in some other way. Such a change would be difficult or impossible to detect in a code review, so the chances are good that it would be approved and merged into production, producing a binary that doesn't work.

Run through the code and find declared constants whose values matter (don't worry about constants whose specific values don't matter as long as they're different from something else), and write short tests verifying that they have the proper value. Like this:

```
#[test]
pub fn MY_CONSTANT_has_correct_value() {
    assert_eq(MY_CONSTANT, 1234);
}
```

Some of the constant values may already be effectively tested, especially in integration tests that talk to the outside world. Those tests are more valuable than the kind above: don't worry about writing separate unit tests for these.

**Comment by utkarshg6** [comment]
Yes, @dnwiebe ! This card looks perfect for me. I'd love to pick it up.


Thank you for offering such a nice card. 🙏
