### ISSUE TITLE
Differentiate between 'No 3 hop route found' and 'Connection to Entry Node failed'

### ISSUE THREAD

**Issue by anonmate** [MASQ-Project/MASQ-Node-issues#574]
Right now it's annoying that in the UI we have no way of knowing which one of the following is true: 

• a 3 hop route wasn't found
• if the entry node connection failed and we need to grab a new entry node ID.

Because, the messaging in the node log is the same regardless of whether a 3 hop route wasn't found, or the entry node plainly was not online on the network at all. There's also no UI messaging for errors and I know that links to another card that has priority as of writing this.

It would be extremely helpful if we knew if our initial entry into the network failed to:

• Connect to the initial Node ID
• Further than this, if our 'first hop' connection, is successfully returning any traffic for us as a test

Right now, you enter a node ID and cross your fingers, and many users think that the software just doesn't work (unless they are savvy enough to look at the Node Logs and think to put a new ID in, which most are not).

Perhaps regardless of 3 hop route failure, or initial entry node connection failure – the outcome for us is probably the same – We must prompt the user to either enter a new one, or fetch a new one automatically for them from our Node IDs API.

**Comment by bertllll** [comment]
@kauri-hero 
I'm a bit concerned that you prioritized this before a talk with developers.
My opinion is that this is technically a backlog. It needs a ground of #349.
I launched the works, with the cited card assigned to @utkarshg6, I will support him closely while he's trying to work it out. (I've been stoking up the boiler with engagement of @utkarshg6, but he's strong :laughing:     )

**Comment by bertllll** [comment]
@kauri-hero
I'm a bit concerned that you prioritized this before a talk with developers.
My opinion is that this is technically a backlog. It needs the proper ground of https://github.com/MASQ-Project/Node-issues/issues/349.
I launched the works, with the cited card assigned to @utkarshg6, I will support him closely while he's trying to work it out. (I've been stoking up the boiler with engagement of @utkarshg6, but he's strong :laughing:  )

**Comment by kauri-hero** [comment]
Thanks Bert that's my mistake.
I was considering whether it was able to be considered as part of any log error reporting but I didn't think it would be played anytime in next week or so.

You can place in backlog immediately

**Comment by utkarshg6** [comment]
# Information Discussed on the meeting held on 24th March 2022

## Reasons why a Node is not able to connect to the network:
1) The network in too small and because of that it can't get minimum hop count of 3 hops, which is a mandatory limit.
2) There occurred a problem connecting to a new neighbor. It might be possible due to the following reasons:
    a) Neighbors don't accept us
    b) We're stuck with a dead node
    
## Types of Messages (might be used in this problem):

1) Start Message: This message is sent to the neighborhood to tell that it has started.

## CORES Packages

- It stands for CORES (client, origin, relay, exit, server). More information can be found [here](https://docs.masq.ai/masq/faq/faq-security/detect-an-exit-node).
- It is a byte structured, heavily encrypted package. Without a decryptor, it is just a bucket of bits.
- There are 3 states of CORES package in the memory.
    1. Incipient Cores Package - A newly created CORES package about to be sent to the Hopper.
    2. Live Cores Package - The package that gets passed through the wire.
    3. Expired Cores Package - CORES package that has traversed the Network.

## Some Important Conditions

* Debut Gossip to first neighbor fails on a TCP level
* Debut Gossip succeeds on a TCP level, but fails to produce a connection because
    * Some other Node accepts the Debut but fails to respond
    * Every response is Pass Gossip, resulting in no actual connection
* Debut Gossip worked fine, Node is fully connected, but Network is too small to accommodate minimum hop count
* Node is fully connected, warmed up, and online, and browser traffic can begin

**Comment by utkarshg6** [comment]
# Testing outline


## What's new?

Whenever a Node will attempt to make a connection to the network, the Node will send a _fire-and-forget message to the UI_, at exactly these two instances:
- `ConnectedToNeighbor`: The node has established a neighborship with at least one new node.
- `ThreeHopsRouteFound`: The node has found a three hops route, and now it's possible to relay data.

### Constraints:

1. The modifications are only made inside the `Node`, and as of writing this comment no changes were made to the UI for handling these messages.
2. Under the PR of this card, only the advancing transitions are implemented. The regressing transitions aren't covered yet. So, it's possible to receive a message when a transition takes place from `ConnectedToNeighbor` to `ThreeHopsRouteFound` but vice versa is not true. Notice that there are no backward arrows in the below diagram.

![Overall Connection Status V2](https://user-images.githubusercontent.com/32920299/168798144-d25007af-8848-4c8c-a11b-2102ea7dee33.jpeg)

_Neighborship Established (a)_: When a Node receives a gossip (introduction or standard) which results in the establishment of full neighborship.

_Can Make Routes (b)_: The `check_connectedness()` returned `true`, hence 3 hops route found.

The only possible event that can trigger any of these two messages, is when there's a change in neighbourhood database, which is caused whenever a node receives a gossip. It is possible that single gossip can cause both of these transitions. For example, an introduction gossip can cause both the establishment of neighborship, and it can also provide a 3 hops route.

## Possible Ideas for Testing

### Cases to Consider

Case 1 -> The network is too small, 3 hops route does not exists.
Case 2 -> The network is big enough, 3 hops route exists.


### Steps

Step 1 -> Build a network with different permutations for the following two cases.
Step 2-> Check whether the Node sends the fire-and-forget message to the UI, when it's attempting to establish a connection the masq network.
