### ISSUE TITLE
Past Neighbors doesn't initiate reconnecting to previous neighbor

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#577]
This appears to be functioning, but there are areas of improvement for Gossip, graceful shutdown and culling dead nodes

@kauri-hero 
**To review this card and determine if it should remain open**

Its a going concern that neighborhood structures appear more easily destroyed by incoming nodes connections that have connected before, by way of entry nodes already connected together in previously a stable mesh.

My observation is this:
Upon entry, Gossip debuts, introductory passes and acceptance seem to work fine on the initial connection by a new node neighbor. (Logs support this)
But once the Node neighbor disconnects, if they reconnect to the same neighbor again, they never manage to connect to more than just their entry Node specified on startup.

Its hard to verify without further inspection of the database in sqlite, but I'm noticing that at least on CLI the `configuration <db-password>` command is only ever showing one past neighbor stored, instead of an array.

This leads me to believe the hotfix on GH-571 may need to be inspected to ensure that past neighbors can be stored as an array (like it was previous before around GH-477 merge to master) 

The most interesting aspect of this is I decided to start looking at the logs with --log-level trace to see if I could construct the graph viz again from my old toolkit, which can show the 1 or 2 way connections on Node neighbors using the digraph gossip output.

The reason I suspect these issues around 'Past Neighbors' still exist is that the gossip digraph still shows some of the original neighbors before shutdown

**Comment by bertllll** [comment]
We will probably never resolve this without a log-file with the needed details.

**Comment by bertllll** [comment]
@kauri-hero 
We will probably never resolve this without a log-file with the needed details.

If we can read what was happening during the time when the Nodes were trying to get together into a neighborhood will be able to tell you more.

**Comment by kauri-hero** [comment]
Absolutely @bertllll I have prepared logs and info and will post in our private channel - it has sensitive information in it
