### ISSUE TITLE
Gossip Handler Temp Memory

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#598]
Will be handled in #574 with confirmation fro @utkarshg6 and @dnwiebe 

From discussion on Pass gossip machinery.

Dan:
Something we haven't done, but that would probably not go amiss, is to have the Gossip handler remember, at least for a time, which Nodes it had passed to which Nodes; and if a Node came by that it had seen before, and the Pass machinery indicated that it should be Passed to the same Node it was Passed to before, the Gossip handler should just throw the Debut on the floor and not process it. That might break some loops.

may overlap with #574 , as that addresses connection state

**Comment by bertllll** [comment]
This is going to be handled within the other mentioned card. It's planned.
