### ISSUE TITLE
Forestall server responses to broken browser streams

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#608]
__Background:__
- A browser commonly maintains several TCP streams between it and each of a collection of servers.
- When one end of a TCP stream is closed, the holder of the other end is informed immediately.
- Across the MASQ Network, since the browser is not connected directly to any HTTP server, each of these virtual streams has to be modeled by two real streams: one from the browser to the originating Node, and one from the exit Node to the server.
- When the browser or the server closes its end of one of these real streams, the MASQ Network has to close its end of the other real stream as quickly as possible. This is accomplished by sending a CORES package containing a `ClientResponsePayload_0v1` with a zero-length `SequencedPacket` having a `last_data` flag set to `true`.
- When a browser first loads a page, it opens many streams to the server, one for each downloadable resource mentioned on the page.
- If the user clicks to another page before all those resources arrive from their servers, the browser closes all the existing streams, to make the servers stop sending information that will never be displayed, and begins showing the next page instead.

__Issue:__
When the browser closes existing streams to the originating Node, the Node is not sending the shutdown CORES packages to the servers on the other ends of those streams. This means the servers are continuing to send their data, which arrives at the originating Node and can find no existing stream to get back to the browser, and is therefore thrown away after generating a `WARN` log.

This is bad for two reasons: first, we're being bad neighbors for the servers, which are spending time and bandwidth shoveling out data that we already know will be thrown away. Second, our user is paying for that data to be exited and routed, even though we already know it will be thrown away.

Look through the code for the string `TODO GH-608`. Modify the Node so that whenever it senses that the browser has closed a stream, it makes sure a `last_data: true` packet is sent to the corresponding exit Node.

**Comment by utkarshg6** [comment]
Hey, @bertllll!

I found this code written by you.

I'm talking about this function `handle_normal_client_data()`. It's in the file `node/src/proxy_server/mod.rs` at Line Number 859. It's inside the implementation block of `IBCDHelper` for `IBCDHelperReal`.

It seems that your code is doing exactly what this card demands. It would be helpful to know If you can confirm that you've written this code while solving either the same or similar problem.

Thanks! 🙏

**Comment by utkarshg6** [comment]
Hi @kauri-hero!

In the discussion with @dnwiebe and @bertllll it was concluded, that the Node contains the code that is necessary for this card. 

We must close this card now.
