### ISSUE TITLE
Add Connection Status Interrogation

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#622]
If a UI connects to a Node after it has sent all its `UiConnectionChangeBroadcast` messages, there is no way the UI can discover the Node's connection status. Add a `Conversation` transaction to the Node and to `masq` that allows the UI to interrogate the Node about its connection status at any time and get a response.

**Comment by utkarshg6** [comment]
# Testing Outline

- There is a new command introduced named `connectionStatus`, which can be used to interrogate the Node about the connection status of the Node and the Node will return a stage in return.

- You may refer to these docs - https://github.com/MASQ-Project/Node/blob/GH-574/USER-INTERFACE-INTERFACE.md#connectionstatus

- The JSON format that is written in this docs might be a bit different to what's seen on the UI side. In that case, let me know the correct format of JSON received on the other end. I'll update it in the docs.

- Also, this card is the child of the parent card 574. So, you may want to refer that card's testing outline too. You can refer it over here. https://github.com/MASQ-Project/Node-issues/issues/574#issuecomment-1128753919
