### ISSUE TITLE
Gossip Storm Avoidance

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#631]
It is observed now that after a network reaches around 50 `standard` Nodes, the gossip activity makes the Node almost unresponsive to CLI commands or handling traffic requests.

Make adjustments to the gossip handling to mitigate this, which could include initial modification to:

avoid handling gossip messages received, that relate to nodes that are too distant (ie outside 3-hops)

Dan - the easiest approach for this is to ignore gossip messages that are 'outside your patch'

**Meeting discussion:**
Possible approach, cut down the database to ensure it only contains your 'patch'

**Comment by kauri-hero** [comment]
When in this state, normal commands via CLI don't seem to get processed.

when using the `shutdown` command, I received this panic and response on Windows 10:

`masq> shutdown
thread 'main' panicked at 'Unexpected error: please report to us: No response from Node or Daemon after 60000ms (Code 8000_0000_0000_0006)', D:\a\Node\Node\masq\src\commands\shutdown_command.rs:67:17
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
thread '<unnamed>' panicked at 'called Result::unwrap() on an Err value: PoisonError { .. }', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\linefeed-0.6.0\src\terminal.rs:191:38`

**Comment by kauri-hero** [comment]
strangely enough this could also relate to the #632 card also, as once the gossip storm started, it produced endless logs of the websockets connection error.

Running for roughly twelve hours produced 50 x 100MB compressed log files of just this websocket error in the logs:

`2022-09-08 01:22:44.758 Thd23: WARN: WebSocketSupervisor: 'IoError(Os { code: 10053, kind: ConnectionAborted, message: "An established connection was aborted by the software in your host machine." })' occurred when flushing msg for Client 1`
![image](https://user-images.githubusercontent.com/55721017/189014692-2b959d6b-642a-405f-8e7f-631c39790b34.png)

**Comment by dnwiebe** [comment]
This card is heavily related to #206.
