### ISSUE TITLE
Optimize routing after an exit node is marked undesirable

### ISSUE THREAD

**Issue by utkarshg6** [MASQ-Project/MASQ-Node-issues#674]
An exit node is marked undesirable usually when it fails to resolve the DNS for a certain host name.

So, once the new exit node is picked instead of the current exit node, its possible that the routing charges via this new exit node is more expensive. In this case we might prefer to use the cheaper and older exit node for the hosts that this node is able to access.

Identify which method is more economical:

A) Keep using the current (more expensive) route, because paying the extra money for the new exit Node is worth the performance gain of not having to calculate new routes more frequently.
B) Switch to the route which uses cheaper exit node, and use it for exiting for the future routes, because the performance cost of calculating new routes doesn't outweigh the financial cost of using expensive exit Nodes.

If it turns out the option B is more economical, then design an optimal solution for it. If it turns out that A is sometimes more economical and B is sometimes more economical, design a solution for that.

Note: In case option B is implemented then the multi node test named `dns_resolution_failure_no_longer_blacklists_exit_node_for_all_hosts` must break. If both options are implemented, we'll need more multinode tests.

Deliverables: Attach a comment to this card describing your decision and explaining why you arrived at it. Create a series of small cards to implement the decision.

**Comment by utkarshg6** [comment]
We haven't concluded which approach is more economical, so in my opinion this card should still live.

**Comment by Syther007** [comment]
After card GH-651 is completed this card may not be necessary any more.
Due to automatic retries the way new routes are calculated has changed.
for new requests the node will pick the cheapest exit node

## Test 
multinode_integration_tests/tests/communication_failure_test.rs >> dns_resolution_failure_no_longer_blacklists_exit_node_for_all_hosts

**Comment by kauri-hero** [comment]
This card has been addressed in current work.
