### ISSUE TITLE
Prioritise Volatile Tests in Actions

### ISSUE THREAD

**Issue by utkarshg6** [MASQ-Project/MASQ-Node-issues#730]
When using GitHub Actions to run builds, there's a high likelihood of build failures due to volatile tests. These tests can be volatile because they rely on data from the Blockchain or the Internet.

While we are confident in the accuracy of these tests, occasional failures can still happen. Unfortunately, when they do fail, developers have limited options beyond rerunning the jobs.

Currently, these volatile tests are run towards the end of the process. As a result, a build failure might occur an hour or more into the process. To improve this situation, we may implement the following solution: _run these volatile tests earlier in the process_. If they fail, developers can identify and address issues sooner. Once these volatile tests pass, we can have greater confidence that the build will likely succeed, as the granular tests are very unlikely to fail.

Implementing this solution could be straightforward. I suggest a simple change to the `ci-matrix.yml` file to adjust the test execution order:

Before:

```bash
./ci/all.sh
./ci/multinode_integration_test.sh
```

After:

```bash
./ci/format.sh
./ci/multinode_integration_test.sh
./ci/all.sh
```

This small modification could lead to significant improvements, saving a substantial amount of time in GitHub Actions.

**Comment by utkarshg6** [comment]
Add a parameter which could disable the (`format.sh`/`lint.sh`) execution while running `all.sh`.

**Comment by dnwiebe** [comment]
Remember that the Node has to be built before it can be used by the multinode tests. Hence, the After sequence should look more like this:
```
ci/format.sh
node/ci/build.sh # this line is new
ci/multinode_integration_test.sh
ci/all.sh
```
