### ISSUE TITLE
Harden Receivables Processing: Ignore Unrecognized Benefactors

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#747]
Occasionally, we will find on the blockchain a payment to our earning wallet that comes from a wallet that has no corresponding row in the RECEIVABLES table. At the moment, this causes us problems.

It shouldn't. If we don't know that the payer owes us money, then this payment isn't any of our business and should be ignored. Our earning wallet may be being used for other purposes as well, and we shouldn't interfere with that.

If the issue that prevents an incoming payment from being applied to the RECEIVABLES table is that there's no RECEIVABLES record with that wallet address, the issue should still be logged, but at a low level (say, INFO), and the user should not be bothered, and no new RECEIVABLES record should be created.

**Comment by bertllll** [comment]
The suggestion relates to a closed card that could hardly live on its own (#746). This card turned out to be competent to take the purpose of the older one.

**Comment by bertllll** [comment]
The suggestion relates to a closed card that could hardly live on its own (#746). The card here turned out to be competent to take over the purpose of the older one.

**Comment by bertllll** [comment]
Not with an ease but I've decided to include the functionality the card GH-750 talks about. The architecture since there can be considered all the important stuff containing and complete. I wanted this new architecture to be tailored without creating a future need of an almost inevitable rearchitecture.
