### ISSUE TITLE
[Part of GH-747] Harden Receivables Processing: Delay `start_block` Update

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#750]
At the moment, the way we handle incoming payments is this:

1. We retrieve a cluster of incoming payments from the blockchain: multiple payments may come from the same block.
2. We update the `start_block` property in the `CONFIG` table to point to the first block we haven't searched yet.
3. We run a single database transaction to update all the relevant rows in the `RECEIVABLES` table.

There's a problem here.

We're updating `start_block` too soon. If that database transaction fails, we will have lost the previous value of `start_block`, so we don't know which portion of the blockchain to scan the next time. We should wait to update `start_block` until after the database has been modified, so that the database stays consistent with itself.

This means the update should be done by the `Accountant`, not by the `BlockchainBridge`.

This could cause a bit of architectural consternation, because it's not the job of the `Accountant` to mess with the blockchain, and the concept of a start block is a blockchain issue, not an accounting issue. Think about this and see if you can come up with either a reasonably elegant solution or at least a plausible argument that having the `Accountant` manipulate the `start_block` isn't an architectural problem.

**Comment by bertllll** [comment]
This card has been handled by me in one with GH-747. I've found it easier to do it all together.
