### ISSUE TITLE
[IRRELEVANT] Test Case - possible panic for `--gas-price` missing a value on startup

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#762]
Bert detected that starting Node (without Daemon) without a value for `--gas-price` it panics Node, without any warning from Clap.

Run some testing with binaries in CLI and with daemon to see if this causes panic in most cases.

Discord message for reference:
https://discord.com/channels/@me/851406644163903488/1180206483816841238

**Comment by utkarshg6** [comment]
@Syther007 and I came across a web3 function called `sign_transaction()`. This function can make RPC calls and determine the appropriate values for `nonce` and `gas_price`. This discovery is a game changer as it removes the need to calculate `nonce` and store `gas_price` in the database. If we implement this functionality, there won't be a necessity for the GUI team to handle the sending and receiving of these values.

It makes this card obsolete if we adopt the approach of making RPC calls for `gas_price`, as mentioned earlier.
