### ISSUE TITLE
Implement Amoy Testnet

### ISSUE THREAD

**Issue by bertllll** [MASQ-Project/MASQ-Node-issues#781]
There is a new testnet at Polygon, called Amoy, to replace the soon-deprecated Mumbai. Let's traverse through our codebase and make sure we are not behind in following this change.

**Comment by kauri-hero** [comment]
@bertllll 

Here are formal details for Polygon Amoy test token contract for tMASQ:

Token Contract:
`0xd98c3EBd6B7f9b7cDa2449eCac00d1E5F47a8193`
_(block height: 5323366)_

Contract Link:
https://www.oklink.com/amoy/address/0xd98c3ebd6b7f9b7cda2449ecac00d1e5f47a8193/contract
