### ISSUE TITLE
node UI should detect (and connect to) already running SubstratumNode

### ISSUE THREAD

**Issue by clandest** [MASQ-Project/MASQ-Node-issues#80]
NOTE: Here is a start to being able to get the pid of a running node on Mac and Linux at least.  It will require installing the pstree tool:
pstree | grep "[S]ubstratumNode" | head -1 | sed -E 's/.* ([0-9]+) .*/\1/'

**Comment by dnwiebe** [comment]
This will automatically be part of any self-respecting CLI. This card is probably unnecessary now.
