### ISSUE TITLE
Attempt to create Jenkins Job for Win 32 exe using Win 64 instance

### ISSUE THREAD

**Issue by clandest** [MASQ-Project/MASQ-Node-issues#94]
Check this out: https://github.com/rust-lang-nursery/rustup.rs/pull/421

Should be rewritten into a Cross-compile card

**Comment by dnwiebe** [comment]
This card is probably no longer reasonable; but in its place we should make a card about cross-compilation. That is, create one or more Pipelines jobs to run on Linux VMs but generate code for non-Debian Linuxes, the Raspberry PI, and other exotic and obsolete platforms, possibly including Win32.
